version: '3.9'

services:
  nginx:
    build:
      context: ./nginx
    ports:
      - 8080:80
    restart: always
    depends_on:
      app:
        condition: service_healthy
  app:
    build:
      context: ./nodejs
    volumes:
      - ./nodejs:/app
    ports:
      - 3000:3000
    command: sh entrypoint.sh
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 5s
      timeout: 10s
      retries: 5
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: docker_challange
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .docker/mysql:/var/lib/mysql
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 10s
      retries: 3

    
  